# Generated by Django 5.2.3 on 2025-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_subproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subproducts/'),
        ),
    ]
