# Generated by Django 5.2.3 on 2025-07-02 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.combo'),
        ),
    ]
